### ISSUE TITLE
Transactions are created in allow mode

### ISSUE THREAD

**Issue by friedger** [pseudozach/lnstxbridge-frontend#1]
**Describe the bug**
Transaction should never be submitted in allow mode.

See https://github.com/stacksgov/Stacks-Grants/issues/172#issuecomment-928910403

**Comment by friedger** [comment]
@pseudozach @stacks/transactions has builders for post conditions.

**Comment by pseudozach** [comment]
There's a bit of a background why I ported all those libs into the frontend code, you can read the short version here: https://github.com/blockstack/stacks.js/issues/1096#issuecomment-926963641

For the allow/deny mode since all code/contract is open I hope it's acceptable to keep allow mode now. But I agree eventually I need to clean up the custom code and set proper post conditions and submit in deny mode.

Do you have any pointers on how to calculate max value for a tx? Should I include fee in the postcondition amount or no?

**Comment by friedger** [comment]
> For the allow/deny mode since all code/contract is open I hope it's acceptable to keep allow mode now. 

The user will see a big warning that the tx is unsafe and you should only sign it if you are sure (read the smart contract code). Which can't be expected from the average user.

**Comment by pseudozach** [comment]
fixed by https://github.com/pseudozach/lnstxbridge-frontend/commit/04fb0d2fc53d14646ae84379761c925d0be8e27a

**Comment by friedger** [comment]
Great!
